title: Minimal theme
logo: /imags/logo.jpg
description: Automates psychosocial risk analysis based on NOM-35, featuring an integrated survey, risk assessment, dashboard creation, and PDF report generation, all through an intuitive user interface.
theme: jekyll-theme-minimal
